"""init

Revision ID: a4dc1d7d1fbc
Revises: 83a7fc215b4d
Create Date: 2026-03-31 17:50:14.381064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4dc1d7d1fbc'
down_revision: Union[str, Sequence[str], None] = '83a7fc215b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wish_item_tags',
    sa.Column('wish_item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['wish_item_id'], ['wish_items.id'], ),
    sa.PrimaryKeyConstraint('wish_item_id', 'tag_id')
    )
    op.add_column('friendships', sa.Column('follower_id', sa.Integer(), nullable=True))
    op.add_column('friendships', sa.Column('following_id', sa.Integer(), nullable=True))
    op.add_column('friendships', sa.Column('is_mutual', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('friendships_user_id_friend_id_key'), 'friendships', type_='unique')
    op.drop_constraint(op.f('friendships_user_id_fkey'), 'friendships', type_='foreignkey')
    op.drop_constraint(op.f('friendships_friend_id_fkey'), 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'friendships', 'users', ['following_id'], ['id'])
    op.drop_column('friendships', 'user_id')
    op.drop_column('friendships', 'friend_id')
    op.add_column('wish_items', sa.Column('rate', sa.Integer(), nullable=True))
    op.add_column('wish_items', sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('wish_items', sa.Column('is_gifted', sa.Boolean(), nullable=True))
    op.add_column('wish_items', sa.Column('is_delivering', sa.Boolean(), nullable=True))
    op.add_column('wish_items', sa.Column('is_archieved', sa.Boolean(), nullable=True))
    op.add_column('wish_items', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('wish_items', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish_items', 'created_at')
    op.drop_column('wish_items', 'is_deleted')
    op.drop_column('wish_items', 'is_archieved')
    op.drop_column('wish_items', 'is_delivering')
    op.drop_column('wish_items', 'is_gifted')
    op.drop_column('wish_items', 'expiration_date')
    op.drop_column('wish_items', 'rate')
    op.add_column('friendships', sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('friendships', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key(op.f('friendships_friend_id_fkey'), 'friendships', 'users', ['friend_id'], ['id'])
    op.create_foreign_key(op.f('friendships_user_id_fkey'), 'friendships', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('friendships_user_id_friend_id_key'), 'friendships', ['user_id', 'friend_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('friendships', 'is_mutual')
    op.drop_column('friendships', 'following_id')
    op.drop_column('friendships', 'follower_id')
    op.drop_table('wish_item_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
