"""events

Revision ID: d326e5a4421b
Revises: a4dc1d7d1fbc
Create Date: 2026-04-12 20:51:23.011033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd326e5a4421b'
down_revision: Union[str, Sequence[str], None] = 'a4dc1d7d1fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('notify_days_before', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('description', sa.String(length=512), nullable=True))
    op.add_column('events', sa.Column('notify_days_before', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'notify_days_before')
    op.drop_column('events', 'description')
    op.drop_table('global_events')
    # ### end Alembic commands ###
